vegaEmbed(
"#graph1",
"graphs/graph1.json",
).catch(console.error);
vegaEmbed(
"#graph2",
"graphs/graph2.json",
).catch(console.error);
vegaEmbed(
"#graph3",
"graphs/graph3.json",
).catch(console.error);
vegaEmbed(
"#graph4",
"graphs/graph4.json",
).catch(console.error);
vegaEmbed(
"#graph5",
"graphs/graph5.json",
).catch(console.error);
vegaEmbed(
"#graph6",
"graphs/graph6.json",
).catch(console.error);
vegaEmbed(
"#graph7",
"graphs/graph7.json",
).catch(console.error);
vegaEmbed(
"#graph8",
"graphs/graph8.json",
).catch(console.error);
vegaEmbed(
"#graph9",
"graphs/graph9.json",
).catch(console.error);
vegaEmbed(
"#graph10",
"graphs/graph10.json",
).catch(console.error);
vegaEmbed(
"#graph11",
"graphs/graph11.json",
).catch(console.error);
